#define GAMEWORLDSIZE_X 13
#define GAMEWORLDSIZE_Y 14
#define GRIDELESIZE_X 50 //pixles wide //WINDOW_W / GAMEWORLDSIZE_X
#define GRIDELESIZE_Y 50 //pixles high //WINDOW_H / GAMEWORLDSIZE_Y
#define WINDOW_W GRIDELESIZE_X * GAMEWORLDSIZE_X //logical window size
#define WINDOW_H GRIDELESIZE_Y * GAMEWORLDSIZE_Y